### ISSUE TITLE
can't use gpu mode

### ISSUE THREAD

**Issue by lbtong** [Starlitnightly/omicverse#132]
when i run " ov.settings.gpu_init()"
it returns "Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/_settings.py", line 19, in gpu_init
    rmm.reinitialize(
  File "/home/miniconda3/envs/omicverse/lib/python3.10/site-packages/rmm/rmm.py", line 81, in reinitialize
    mr._initialize(
  File "memory_resource.pyx", line 946, in rmm._lib.memory_resource._initialize
  File "memory_resource.pyx", line 1006, in rmm._lib.memory_resource._initialize
  File "memory_resource.pyx", line 381, in rmm._lib.memory_resource.PoolMemoryResource.__cinit__
MemoryError: std::bad_alloc: out_of_memory: RMM failure at:/__w/rmm/rmm/include/rmm/mr/device/pool_memory_resource.hpp:424: Maximum pool size exceeded"
how should i do to fix this error?thank you very much

**Comment by Mei918** [comment]
libc.so.6: version `GLIBC_2.28' not found , I got this error

**Comment by Starlitnightly** [comment]
Maybe you need to update the system

**Comment by H1207953831** [comment]
Hi， I'm here again。
I looked at the source code and tried to simulate it in another file myself。
Found that you only need to set `managed_memory` to `False`，and no error will be reported.
