### ISSUE TITLE
ImportError: cannot import name '_IGraphLayout' from 'scanpy.plotting._utils'

### ISSUE THREAD

**Issue by xiaoli-0709** [Starlitnightly/omicverse#154]
I encountered a problem while testing whether omicverse was successfully installed, and the complete error message is as follows：

```
python -c "import omicverse"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/omicverse/__init__.py", line 11, in <module>
    from . import bulk,single,utils,bulk2single,pp,space,pl,externel
  File "/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/__init__.py", line 8, in <module>
    from ._Gene_module import pyWGCNA
  File "/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/_Gene_module.py", line 21, in <module>
    from ..utils import pyomic_palette,plot_network
  File "/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/omicverse/utils/__init__.py", line 33, in <module>
    from ._scatterplot import *
  File "/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/omicverse/utils/_scatterplot.py", line 34, in <module>
    from scanpy.plotting._utils import (
ImportError: cannot import name '_IGraphLayout' from 'scanpy.plotting._utils' (/data1/home/lijh/.conda/envs/omicverse/lib/python3.10/site-packages/scanpy/plotting/_utils.py)
```

Versions:
scanpy==1.10.3 ;omicverse==1.6.6

**Comment by xiaoli-0709** [comment]
It's seems that the version of scanpy=1.10.3 is confict with the omicverse. I install scanpy=1.9.8 instead and solve the problem.

**Comment by liuxiawei** [comment]
Same problem happend.Thanks
