### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.generation'

### ISSUE THREAD

**Issue by komais** [Starlitnightly/omicverse#183]
**Describe the bug**
ModuleNotFoundError: No module named 'transformers.generation'

>>> import omicverse as ov
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/conda/lib/python3.10/site-packages/omicverse/__init__.py", line 11, in <module>
    from . import bulk,single,utils,bulk2single,pp,space,pl,externel
  File "/software/conda/lib/python3.10/site-packages/omicverse/bulk/__init__.py", line 8, in <module>
    from ._Gene_module import pyWGCNA,readWGCNA
  File "/software/conda/lib/python3.10/site-packages/omicverse/bulk/_Gene_module.py", line 24, in <module>
    from ..externel.PyWGCNA.wgcna import pyWGCNA
  File "/software/conda/lib/python3.10/site-packages/omicverse/externel/__init__.py", line 1, in <module>
    from . import (scSLAT,CEFCON,mofapy2,GNTD,spaceflow,STT,
  File "/software/conda/lib/python3.10/site-packages/omicverse/externel/scMulan/__init__.py", line 1, in <module>
    from .model.model import MulanConfig, scMulanModel
  File "/software/conda/lib/python3.10/site-packages/omicverse/externel/scMulan/model/model.py", line 8, in <module>
    from transformers.generation.utils import SampleDecoderOnlyOutput
ModuleNotFoundError: No module named 'transformers.generation'
>>> import transformers
>>> transformers.__version__
'4.17.0'

thank you very much

**Comment by Starlitnightly** [comment]
Why not update the version of transformer, maybe it need to larger than `4.30.2`
