### ISSUE TITLE
Error reported when running gsea_obj.feedback function

### ISSUE THREAD

**Issue by Zstark11** [Starlitnightly/omicverse#187]
Error reported when running gsea_obj.feedback function

```
rnk=dds.ranking2gsea()
gsea_obj=ov.bulk.pyGSEA(rnk,pathway_dict)
enrich_res=gsea_obj.enrichment()

```
report errors
```
Traceback (most recent call last):
  File "/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-f9a5b288f443>", line 1, in <module>
    enrich_res=gsea_obj.enrichment()
  File "/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py", line 386, in enrichment
    pre_res=geneset_enrichment_GSEA(self.gene_rnk,self.pathways_dict,
  File "/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py", line 124, in geneset_enrichment_GSEA
    pre_res = prerank(rnk=gene_rnk, gene_sets=pathways_dict,
  File "/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/omicverse/externel/gseapy/gsea.py", line 1039, in prerank
    pre = Prerank(rnk, gene_sets, outdir, pheno_pos, pheno_neg,
  File "/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/omicverse/externel/gseapy/gsea.py", line 484, in __init__
    self._logger = log_init(outlog=logfile,
TypeError: log_init() got an unexpected keyword argument 'outlog'
```
Version information
Python 3.10, scanpy 1.10.3, omicverse 1.6.7, scvi-tools 1.2.0, scvi 0.6.8，
Is it related to the version of scvi tools？

**Comment by Starlitnightly** [comment]
Could you update the version of omicverse to `1.6.8`
