### ISSUE TITLE
Installation Recommendation for people using Conda or pip 

### ISSUE THREAD

**Issue by mugpeng** [Starlitnightly/omicverse#60]
I use ubuntu:
```
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-124-generic x86_64)
```

And when I follow the installation tutorial [Installation - omicverse Readthedocs](https://omicverse.readthedocs.io/en/latest/Installation_guild/#apple-silicon-prerequisites)
by conda, I encounter:
```
torch_sparse/_version.so: undefined symbol
```

Then I go through the [Installation — pytorch_geometric documentation](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html), and [PyTorch](https://pytorch.org/) to install pytorth with recommendation basing on my selection. But I still get the error when install pytorth.

Upon further investigation, I discovered that the issue could potentially be related to Conda, which has a complex dependency checking process.

Then I choose pip to finish the prerequisite part. My server is running ubuntu and only have cpus.

Here is my command:
![image](https://github.com/Starlitnightly/omicverse/assets/52995448/eafabc35-2833-4716-ae69-93955684c66c)
![image](https://github.com/Starlitnightly/omicverse/assets/52995448/ec01f1b0-d772-46d1-a52c-4226f1e63088)

```
mamba create -n omicverse python=3.8
conda activate omicverse

pip install torch_geometric
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu

mamba install omicverse -c conda-forge
```

```
>>> import omicverse

   ____            _     _    __
  / __ \____ ___  (_)___| |  / /__  _____________
 / / / / __ `__ \/ / ___/ | / / _ \/ ___/ ___/ _ \
/ /_/ / / / / / / / /__ | |/ /  __/ /  (__  )  __/
\____/_/ /_/ /_/_/\___/ |___/\___/_/  /____/\___/

Version: 1.5.7, Tutorials: https://omicverse.readthedocs.io/
>>>
```

Hope it can help you during your installation.

**Comment by Starlitnightly** [comment]
Thanks for the suggestion, the latest version of the tutorial has added some modified definitions. However, I still feel that the latest tutorial raises questions.

**Comment by yifanfu01** [comment]
Hi thanks and I install these without error. 
But when I try to import OV
it reports
```

Traceback (most recent call last):
  File "py_test.py", line 17, in <module>
    import omicverse as ov
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/__init__.py", line 11, in <module>
    from . import bulk,single,mofapy2,utils,bulk2single,pp,space,pl,spatrio
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/bulk/__init__.py", line 8, in <module>
    from ._Gene_module import pyWGCNA
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/bulk/_Gene_module.py", line 14, in <module>
    import scanpy as sc
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/__init__.py", line 45, in <module>
    from . import datasets, experimental, external, get, logging, metrics, queries
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/datasets/__init__.py", line 5, in <module>
    from ._datasets import (
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/datasets/_datasets.py", line 15, in <module>
    from ..readwrite import read, read_visium
  File "/public/home/qiujiangdong/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/readwrite.py", line 1015
    ) as t,
      ^
SyntaxError: invalid syntax
```

**Comment by Starlitnightly** [comment]
Now you can use `.sh` install automatically.

```shell
#Only for Linux
curl -sSL https://raw.githubusercontent.com/Starlitnightly/omicverse/refs/heads/master/install.sh | bash -s
Th
```
