### ISSUE TITLE
Encounter Error When Installing OmicVerse on Ubuntu 22.04 [Preparing metadata (setup.py) ... error]

### ISSUE THREAD

**Issue by michael-yuyuan** [Starlitnightly/omicverse#65]
## Description:

- Command Used: pip install -U omicverse
- Outcome: Error occurred.
- Attempted Solution:
  - Tried using pip install omicverse.
  - Tested with Python version 3.11.5.
  - Pip version: 23.3.1.
  - Installation sources from Alibaba Cloud and Tsinghua were attempted.
- Also attempted installation within a miniconda environment (conda version 24.1.2).
- Issue Persisting: Error persists despite multiple attempts.
- Request: Assistance needed to resolve the installation issue. Thank you!

---
```python
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting omicverse
  Using cached https://mirrors.aliyun.com/pypi/packages/e8/97/20c42efca3264918868942a7c0b9b621897d91b4331491a88381fa4bfd7f/omicverse-1.5.8-py3-none-any.whl (2.1 MB)
......
Collecting s-gd2>=1.8.1 (from phate>=1.0->omicverse)
  Using cached https://mirrors.aliyun.com/pypi/packages/47/fb/d85945c9eceaba37552b369c819945d9e9413240643ef49ef3395c357243/s_gd2-1.8.1.tar.gz (53 kB)
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      /root/miniconda3/lib/python3.11/site-packages/setuptools/dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'index-url' will not be supported in future
              versions. Please use the underscore name 'index_url' instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /root/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement Cython (from versions: none)
      ERROR: No matching distribution found for Cython
      Traceback (most recent call last):
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/root/miniconda3/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpad8kd3ah', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'Cython']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ox08rr7i/s-gd2_e3cbc838b7e742a5af5b5362fcba85a4/setup.py", line 61, in <module>
          setup(
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 662, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.11/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/root/miniconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpad8kd3ah', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'Cython']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
’‘’
hint: See above for details.
Note: you may need to restart the kernel to use updated packages.

**Comment by Starlitnightly** [comment]
Hi,

This happens when you do not include libssl-dev during the installation of buildozer dependences.

```shell
sudo apt-get update
sudo apt-get install libssl-dev
```

**Comment by michael-yuyuan** [comment]
Hi,

I successfully installed the 'omicverse' module, but when I import it, an unexpected error occurred. The error message is:

```python
(omicverse) root@iZ2vcf00l:~# python3
Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import omicverse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/omicverse/__init__.py", line 11, in <module>
    from . import bulk,single,mofapy2,utils,bulk2single,pp,space,pl
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/omicverse/single/__init__.py", line 20, in <module>
    from ._cefcon import pyCEFCON,convert_human_to_mouse_network,load_human_prior_interaction_network,mouse_hsc_nestorowa16
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/omicverse/single/_cefcon.py", line 20, in <module>
    from ..CEFCON.cell_lineage_GRN import NetModel
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/omicverse/CEFCON/__init__.py", line 6, in <module>
    from .cell_lineage_GRN import NetModel
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/omicverse/CEFCON/cell_lineage_GRN.py", line 17, in <module>
    import torch_geometric as pyg
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/__init__.py", line 13, in <module>
    import torch_geometric.datasets
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/datasets/__init__.py", line 101, in <module>
    from .explainer_dataset import ExplainerDataset
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/datasets/explainer_dataset.py", line 9, in <module>
    from torch_geometric.explain import Explanation
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/__init__.py", line 3, in <module>
    from .algorithm import *  # noqa
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/algorithm/__init__.py", line 1, in <module>
    from .base import ExplainerAlgorithm
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/algorithm/base.py", line 14, in <module>
    from torch_geometric.nn import MessagePassing
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 5, in <module>
    from .to_hetero_with_bases_transformer import to_hetero_with_bases
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/to_hetero_with_bases_transformer.py", line 9, in <module>
    from torch_geometric.nn.conv import MessagePassing
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 8, in <module>
    from .gravnet_conv import GravNetConv
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/conv/gravnet_conv.py", line 13, in <module>
    from torch_cluster import knn
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/root/miniconda3/envs/omicverse/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_cluster/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
>>>
```python

**Comment by DBinary** [comment]
Hello Michael,

Could you please provide me with the details regarding the version of PyG you have installed? It is important for us to resolve this error.

**Comment by Starlitnightly** [comment]
Hi,

Here's my installation process on the new machine.

```shell
mamba install jax jaxlib -c conda-forge
pip3 install torch torchvision torchaudio
pip3 install torch_geometric
pip3 install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.2.0+cu121.html
pip3 install -U omicverse
```

Sincerely,

Zehua

**Comment by michael-yuyuan** [comment]
Hello,

Today, I finally arrived at the laboratory with excitement, ready to address this issue. When I attempted to import torch_geometric to check the version of PyG, I was embarrassed to encounter an error with this operation as well. I am a graduate student majoring in academic research in clinical medicine, and I have studied Python and Linux systems. By the way, I would like to mention that I am using an Alibaba Cloud ECS server without a GPU.

Best regards,

```python
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/__init__.py", line 13, in <module>
    import torch_geometric.datasets
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/datasets/__init__.py", line 101, in <module>
    from .explainer_dataset import ExplainerDataset
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/datasets/explainer_dataset.py", line 9, in <module>
    from torch_geometric.explain import Explanation
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/__init__.py", line 3, in <module>
    from .algorithm import *  # noqa
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/algorithm/__init__.py", line 1, in <module>
    from .base import ExplainerAlgorithm
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/explain/algorithm/base.py", line 14, in <module>
    from torch_geometric.nn import MessagePassing
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 5, in <module>
    from .to_hetero_with_bases_transformer import to_hetero_with_bases
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/to_hetero_with_bases_transformer.py", line 9, in <module>
    from torch_geometric.nn.conv import MessagePassing
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 8, in <module>
    from .gravnet_conv import GravNetConv
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_geometric/nn/conv/gravnet_conv.py", line 13, in <module>
    from torch_cluster import knn
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/root/miniconda3/envs/omicverse/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/miniconda3/envs/omicverse/lib/python3.9/site-packages/torch_cluster/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
```

**Comment by michael-yuyuan** [comment]
Now，I am preparing to reinstall the operating system and follow the steps outlined in [the installation guide](https://omicverse.readthedocs.io/en/latest/Installation_guild/#4-install-pytorch-and-pyg-at-first) to install PyTorch and PyG once again.

**Comment by michael-yuyuan** [comment]
Everyone, I have successfully installed it. It was an issue with my PyG version. Below is how I successfully installed it:

# miniconda3
```shell
conda create -n omicverse python=3.9
conda activate omicverse
```

# install mamba
```shell
conda install mamba -c conda-forge
```

# install jax jaxlib
```shell
mamba install jax jaxlib -c conda-forge
```

# install torch 
```shell
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu --force-reinstall
```

# install pyg_lib,torch_scatter,torch_sparse,torch_cluster,torch_spline_conv
```shell
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.2.1+cpu.html --force-reinstall
``` 

# terminal：
```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
omicverse 1.5.8 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.
```

# reinstall numpy 1.23：
```shell
pip install numpy==1.23
```

# install torch_geometric：
```shell
pip3 install torch_geometric
```

# finally install omicverse：
```shell
pip install -U omicverse --use-pep517
pip install -U numba
```

**Comment by DBinary** [comment]
Congratulations! 
Please contact us if you have any questions on Omicverse or CEFCON.

**Comment by michael-yuyuan** [comment]
Dear developers,

omicverse is an excellent tool for bioinformatics analysis in Python. However, I haven't systematically studied mathematical statistics. I only took a simple course called "Medical Statistics" during my undergraduate and graduate studies, where I learned some basic principles, including Student's t-test, Analysis of Variance, Chi-square Test, and Rank Sum Test. When using this tool, I don't want to just be a "package caller". I also want to understand why I need to do certain things, what operations I performed on my data, and what resources I should refer to. Do you have any recommended textbooks or documentation for someone like me who is not from a statistical or computer science background? As a non-statistician and non-computer scientist researcher, I have a certain foundation in C language, C#, and Python programming.

I want to use omicverse for performing differential gene expression analysis and transcriptome sequencing data analysis in future molecular biology experiments. Of course, I will cite your work as a reference and express my gratitude to your team in my article (if it can be successfully published😀).

Thank you，
Michael Yu

**Comment by Starlitnightly** [comment]
> Dear developers,
> 
> omicverse is an excellent tool for bioinformatics analysis in Python. However, I haven't systematically studied mathematical statistics. I only took a simple course called "Medical Statistics" during my undergraduate and graduate studies, where I learned some basic principles, including Student's t-test, Analysis of Variance, Chi-square Test, and Rank Sum Test. When using this tool, I don't want to just be a "package caller". I also want to understand why I need to do certain things, what operations I performed on my data, and what resources I should refer to. For example, when performing differential gene screening, what is the difference between using t-test and using other methods? How is the normalization of data within a group accomplished? Why normalize?
> 
> So, do you have any recommended textbooks or documentation for someone like me who is not from a statistical or computer science background? As a non-statistician and non-computer scientist researcher, I have a certain foundation in C language, C#, and Python programming.
> 
> I want to use omicverse for performing differential gene expression analysis and transcriptome sequencing data analysis in future molecular biology experiments. Of course, I will cite your work as a reference and express my gratitude to your team in my article (if it can be successfully published😀).
> 
> Thank you， Michael Yu

Hi,

Thanks for your support for omicverse, if you want to learn omicverse systematically. There is a tutorial named ‘Single cell best practices‘ (https://www.sc-best-practices.org/preamble.html). And if your Chinese is well, you can also read our tutorial(https://single-cell-tutorial.readthedocs.io/zh/latest/)

Sincerely,

Zehua

**Comment by chenwlearning** [comment]
wo di guaiguai. the installation process is so terrible. i followed many instructions to install it but it still can't work properly. i don't know why. the most frequent issue is scvi-tool.
