### ISSUE TITLE
Conflict on scanpy and omicverse

### ISSUE THREAD

**Issue by yifanfu01** [Starlitnightly/omicverse#74]
I installed omicverse on the HPC with pip, followed the suggestion mentioned on #60 
and when import omicverse, i met errors:
```
Traceback (most recent call last):
  File "py_test.py", line 17, in <module>
    import omicverse as ov
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/__init__.py", line 11, in <module>
    from . import bulk,single,mofapy2,utils,bulk2single,pp,space,pl,spatrio
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/bulk/__init__.py", line 8, in <module>
    from ._Gene_module import pyWGCNA
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/omicverse/bulk/_Gene_module.py", line 14, in <module>
    import scanpy as sc
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/__init__.py", line 45, in <module>
    from . import datasets, experimental, external, get, logging, metrics, queries
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/datasets/__init__.py", line 5, in <module>
    from ._datasets import (
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/datasets/_datasets.py", line 15, in <module>
    from ..readwrite import read, read_visium
  File "/public/home/USER/.conda/envs/omicverse/lib/python3.8/site-packages/scanpy/readwrite.py", line 1015
    ) as t,
      ^
SyntaxError: invalid syntax
```

I think it is due to conflict of scanpy. I used `scanpy 1.10.1`
Then I reinstall scanpy to `1.9.8` it will solved. But i choose to uninstall and re-install, so some dependencies are not available.
```
Installing collected packages: scanpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
omicverse 1.5.9 requires ctxcore>=0.2, which is not installed.
omicverse 1.5.9 requires datetime>=4.5, which is not installed.
omicverse 1.5.9 requires ERgene>=1.2, which is not installed.
omicverse 1.5.9 requires graphtools>=1.5, which is not installed.
omicverse 1.5.9 requires gseapy==0.10.8, which is not installed.
omicverse 1.5.9 requires ktplotspy>=0.1, which is not installed.
omicverse 1.5.9 requires metatime>=1.3.0, which is not installed.
omicverse 1.5.9 requires mofax>=0.3, which is not installed.
omicverse 1.5.9 requires phate>=1.0, which is not installed.
omicverse 1.5.9 requires pybedtools>=0.8.1, which is not installed.
omicverse 1.5.9 requires pybind11>=2.10, which is not installed.
omicverse 1.5.9 requires pydeseq2<=0.4.0,>=0.3, which is not installed.
omicverse 1.5.9 requires python-dotplot>=0.0.1, which is not installed.
omicverse 1.5.9 requires scrublet>=0.2, which is not installed.
omicverse 1.5.9 requires pygam==0.8.0, but you have pygam 0.9.1 which is incompatible.
Successfully installed scanpy-1.9.8

```
But it seems I haven't met other errors.
I'm wondering whether it occurs due to conflict of specific version of `scanpy`

BTW, i tried to sololy install STALigner, but I falled XD.

**Comment by Starlitnightly** [comment]
Hi, 

you can try install by: 
```
conda create -n omicverse python=3.10
conda activate omicverse
conda install mamba -c conda-forge
mamba install jax jaxlib -c conda-forge
pip3 install torch torchvision torchaudio
pip3 install torch_geometric
pip3 install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.3.0+cu121.html
pip3 install -U omicverse
```

**Comment by yifanfu01** [comment]
Hi @Starlitnightly 
I install successfully.
But a huge problem:
when import pyg_lib, it will occur wrong discussed in https://github.com/pyg-team/pyg-lib/issues/266
Would you plz kindly tried to fixed?

**Comment by Starlitnightly** [comment]
> Hi [@Starlitnightly](https://github.com/Starlitnightly) I install successfully. But a huge problem: when import pyg_lib, it will occur wrong discussed in [pyg-team/pyg-lib#266](https://github.com/pyg-team/pyg-lib/issues/266) Would you plz kindly tried to fixed?

Actually, i don't install `pyg_lib` in my enviroment.
